networks:
  wedding-network:
    name: wedding-network

services:
  wedding-db:
    build:
      context: .
      dockerfile: dockerfiles/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wedding_db
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./dockerfiles/mysql/my.cnf:/etc/my.cnf
      - ./dockerfiles/mysql/init:/docker-entrypoint-initdb.d
    networks:
      wedding-network:
        aliases:
          - wedding-db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Go API Service
  wedding-api:
    build:
      context: .
      dockerfile: dockerfiles/go/wedding/Dockerfile.go_local
    ports:
      - "8088:8080"
      - "3468:2345" # Port dành cho công cụ debug Delve
    volumes:
      - ./src:/go/app
    tty: true
    depends_on:
      wedding-db:
        condition: service_healthy
    networks:
      wedding-network:
        aliases:
          - backend.wedding.internal

  # Swagger UI Document
  wedding-swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8098:8080"
    environment:
      API_URL: openapi.yaml
    volumes:
      - ./src/generated/openapi/openapi/openapi.yaml:/usr/share/nginx/html/openapi.yaml
    networks:
      - wedding-network

  # HTTPS Proxy for API and Swagger UI
  wedding-https-proxy:
    image: steveltn/https-portal:1
    ports:
      - "8085:80"
      - "8446:443"
    environment:
      STAGE: local
      DOMAINS: "api.wedding.internal -> http://wedding-api:8080, swagger.wedding.internal -> http://wedding-swagger-ui:8080"
    networks:
      - wedding-network

  # Node toolchain for OpenAPI code generation and misc frontend tasks
  wedding-node:
    build:
      context: .
      dockerfile: dockerfiles/node/Dockerfile
    volumes:
      - ./src/wedding-openapitools.json:/app/wedding-openapitools.json
      - ./src/openapi:/app/openapi
      - ./src/generated:/app/generated
    tty: true
    ports:
      - "3003:3001"
    networks:
      - wedding-network

volumes:
  db_data:
